### ISSUE TITLE
Is this the codebase for KUOSC official page http://kucc.ku.edu.np/kuosc? 

### ISSUE THREAD

**Issue by sigdelsanjog** [kucc1997/kuosc#1]
I saw the GitHub deployment made by GitHub pages and also the URL has codes from this repository. Happy to see this happening, but wanted to know if you guys are planning to make this a template as the official release. The template is so pleasing and UI friendly.
Good Luck.

**Comment by anilkumarshrestha** [comment]
Yes @sigdelsanjog dai. We started this 7-8 months ago. It is still incomplete. @TimilsinaBimal has put lots of effort on it and I think it's time to resume the contribution.

**Comment by TimilsinaBimal** [comment]
There are some issues about responsiveness to solve. I will do that ASAP. Thank you @sigdelsanjog dai for reminding me! and Thank you @anilkumarshrestha dai for giving me this opportunity to contribute to this project.

**Comment by sigdelsanjog** [comment]
@TimilsinaBimal I loved the design and the color palette looks pleasing. Its October and the Hacktoberfest is being celebrated worldwide. If you could commit a few changes and contribute to this repository, it would be nice Also I would like to add a few things:
* Do add this repo in the https://github.com/kucc1997/ku-projects list such that your project gets listed in KU Projects.
* Also work with the KUCC team and launch this theme as the official KUOSC website. @anilkumarshrestha  please facilitate Bimal on this task. 
* Current website: http://kucc.ku.edu.np/kathmandu-university-open-source-community/ has many documents which can be merged in this URL /kuosc and http://kucc.ku.edu.np/kuosc can be made the official link for out community.
@anilkumarshrestha  will you take the lead and propose this change to the Club?
Meanwhile  @TimilsinaBimal you can add the newly registered communities and their annual plan in respective community pages under the KUOSC URL.
Also, you can call for the volunteers at the KUCC group if anyone wants to contribute. Sharing the task, speaking about what you are doing, makes you feel good. That's what Open Source project is all about, 

I wish you all the best.

**Comment by TimilsinaBimal** [comment]
Thank you dai for the suggestion! I will surely do that ASAP.
